### ISSUE TITLE
Usage metadata for documentation

### ISSUE THREAD

**Issue by mgnslndh** [spectresystems/spectre.cli#116]
Ok, so this may be a crazy idea but I'll let you decide its usefulness. 

I was working on some documentation for Cake when I noticed the command line usage documentation. Wouldn't it be nice to be able to get the usage metadata in a format (like perhaps json) that can be consumed by Wyam/Statiq when generating the tool documentation? That way the documentation on the web would be in sync with the actual command line usage model used by the tool.

Now, Cake might not be using Spectre.Cli but for tools that do use Spectre.Cli and, like Cake, generates the documentation using tools like Wyam/Statiq this could perhaps be useful. When I think about this as I write it might be better to have Wyam/Statiq component that can extract this information from the binary.

**Comment by patriksvensson** [comment]
@mgnslndh Not a crazy idea at all. What you want is already built into Spectre.Cli. Try running your app with "./myapp.exe cli xmldoc" and you will get xml back that describes the app usage.

**Comment by mgnslndh** [comment]
That works great! Feature already implemented :) Thanks.

Is this officially supported? I could add a snippet about it in the docs if you like.
