### ISSUE TITLE
Support for default --version on root command

### ISSUE THREAD

**Issue by gsferreira** [spectresystems/spectre.cli#120]
Hi!

I'd like to display the version without providing a command.
Example:

`myCLI --version`.

I managed to do the same by creating a default command but I think that this can be a kind of built-in command from spectre.

**Comment by gsferreira** [comment]
If you have some tips on how to do it, I would love to contribute.

**Comment by patriksvensson** [comment]
@gsferreira I would love to give you some tips, but right now I have a solid idea of how to implement this. Will take a look at it tonight.

**Comment by patriksvensson** [comment]
@gsferreira Just saw my typo above which I've corrected. It should be "I **don't** have a solid idea".

**Comment by patriksvensson** [comment]
@gsferreira I've implemented this. Should be available in 0.48.0 shortly.
