### ISSUE TITLE
Question: Is there a way to build command structure from metadata?

### ISSUE THREAD

**Issue by DarthPedro** [spectresystems/spectre.cli#121]
Hi,
Is there a way to build the app's Command configuration from metadata - using attributes to define the commands and data? Rather than having to call the AddCommand and AddBranch methods?

Also is there a document site hosted somewhere or just the docs in this repo?

This framework looks really good for creating command line apps without all of the boilerplate code.
Thanks!

**Comment by patriksvensson** [comment]
@DarthPedro There is not, and there are currently no plans to support that scenario. It should however be possible for you to build something like this.

**Comment by DarthPedro** [comment]
@patriksvensson thanks. I am considering building a system like that.
Would you consider taking a contribution with that functionality as an add-on module to the Spectre.Cli library?
