### ISSUE TITLE
Support for repeating parameters

### ISSUE THREAD

**Issue by mkevenaar** [spectresystems/spectre.cli#62]
Hi Patrik,

I was wondering if it would be possible to repeat a param that one can enter.

e.g. `myapp.exe myaction --myparam = string1 --myparam = string2`

Thanks,

Maurice

**Comment by patriksvensson** [comment]
@mkevenaar Right now it's not possible, but @daveaglick is currently taking a stab at this so hopefully it will soon be possible (no pressure Dave) 😄

**Comment by daveaglick** [comment]
![giphy](https://user-images.githubusercontent.com/1020407/54218009-126dad80-44c3-11e9-899f-f587ea27bd9b.gif)

**Comment by patriksvensson** [comment]
Resolved by #64

**Comment by mkevenaar** [comment]
When will you release this version?
