### ISSUE TITLE
Support for optional option values

### ISSUE THREAD

**Issue by daveaglick** [spectresystems/spectre.cli#63]
I currently have some options with optional values. For example, turning on a web server: `--serve` (with a default port) and turning on a server with optional port: `--serve 1234`.

This can currently be represented by using two options (a flag + a value) like `--serve --port 1234`. Doing so requires a little extra validation to make sure that they're provided as a pair (I.e., `--port` is never specified without `--serve`). Being able to combine them as a single option is a little cleaner.

One implementation idea is to use a new special value type named something like `OptionalValue<T>` to indicate the option has an optional value and to convey whether it was unspecified, specified without a value, or specified with a value (and what the value was).

**Comment by patriksvensson** [comment]
We could probably support both specifying option values as required and optional, and simply require optional option values to specify an optional parameter.

```
[CommandOption("--foo <VALUE>")]
public int Option { get; set; }

[CommandOption("--foo [VALUE]")]
[DefaultValue(25)]
public int OptionalOption { get; set; }
```

Specifying an optional option would result in a runtime configuration exception.
