### ISSUE TITLE
Add Async suffix to AsyncCommand<T>.Execute()

### ISSUE THREAD

**Issue by daveaglick** [spectresystems/spectre.cli#67]
Just opening for discussion - any thoughts about renaming the `AsyncCommand<T>.Execute(...)` virtual method to `AsyncCommand<T>.ExecuteAsync(...)`? I know the `Async` suffix is generally debatable and people have _strong feelings_ so it's not a hill I'd die on. That said, I personally prefer the suffix - reasoning is summarized pretty well in this thread: https://github.com/dotnet/corefx/issues/31275#issuecomment-407181532

**Comment by patriksvensson** [comment]
Sure thing. I have no objections to this 😊

**Comment by patriksvensson** [comment]
@daveaglick I've fixed this 😄

**Comment by daveaglick** [comment]
Thanks!
