### ISSUE TITLE
Runtime command description override

### ISSUE THREAD

**Issue by daveaglick** [spectresystems/spectre.cli#76]
Now that we can change the behavior of a command at runtime by either passing data to it or doing something different based on the command name, being able to change the description of a command at runtime would be helpful too.

I propose a new `WithDescription(string description)` fluent method to set a description override when registering commands. Anything provided through the method will override an existing attribute-based description on the command class.

If you’re okay with the change I’ll submit a PR.

**Comment by patriksvensson** [comment]
Sounds useful! 👍
