### ISSUE TITLE
Delegate commands

### ISSUE THREAD

**Issue by daveaglick** [spectresystems/spectre.cli#77]
One of the evil things I was able to do with the new command data passing is implement delegate-based commands using a single `DelegateCommand<TSettings>` class and passing the delegate in as data. Is this something that would be cool in-the-box?

Usage would look like this:

```
public class QuoteCommandSettings : CommandSettings
{
    public string Quote { get; set; }
}

public class Program
{
    public static int Main(string[] args)
    {
        var app = new CommandApp();

        app.Configure(config =>
        {
            config.AddCommand<QuoteCommandSettings>(
                (context, settings) => Console.WriteLine(
                    $”Abe Lincoln once said {settings.Quote}”));
        });

        return app.Run(args);
    }
}
```

Any interest in me pulling this in?

**Comment by patriksvensson** [comment]
@daveaglick Sounds like a good idea! 👍
