### ISSUE TITLE
Add non-generic overloads for `AddBranch` and/or `AddCommand`

### ISSUE THREAD

**Issue by agc93** [spectresystems/spectre.cli#86]
If you don't feel this is a good feature, feel free to close, but I just ran into this problem in an app and thought I'd suggest it.

Having an overload for `AddBranch` or `AddCommand` that supports specifying the settings type as a parameter would make it possible to add commands without access to the type parameter (e.g. dynamically added commands).

I'm not sure if this is possible given there'd be no way to know what settings type to pass to the `IConfigurator` but maybe you can think of something I can't!

For example:

```csharp
void AddBranch(string name, Type settingsType, Action<IConfigurator<>> action);
```

--

This is similar to what's available in the Microsoft.Extensions packages:

```csharp
services.AddSingleton<ConfigLoader>();
// is equivalent to 
services.AddSingleton(typeof(ConfigLoader), objectInstance);
```

**Comment by patriksvensson** [comment]
Forgot to get back to you (sorry), but planning to add something like this:

![image](https://user-images.githubusercontent.com/357872/83010737-0400a880-a019-11ea-9255-474cd3d99670.png)

**Comment by patriksvensson** [comment]
@agc93 This has been added in 0.32.0 which should be available shortly.

Import the namespace `Spectre.Cli.Unsafe` and use `SafetyOff()` on a configurator to manually set the types.

```
app.Configure(config =>
{
    config.PropagateExceptions();

    config.SafetyOff().AddBranch("animal", typeof(AnimalSettings), animal =>
    {
        animal.SafetyOn<AnimalSettings>()
            .AddBranch<MammalSettings>("mammal", mammal =>
        {
            mammal.SafetyOff().AddCommand("dog", typeof(DogCommand));
            mammal.AddCommand<HorseCommand>("horse");
        });
    });
});
```
