### ISSUE TITLE
Exitcode 0 with unhandled exception

### ISSUE THREAD

**Issue by mholo65** [spectresystems/spectre.cli#90]
I had a unhandled exception in my application, but exit code was still zero. Shouldn't unhandled exceptions generate an exit code of e.g. -1?

Here's an example output of me just throwing an exception inside command execution. Can make a better repro at some point.
![image](https://user-images.githubusercontent.com/7863439/69240367-fae3da00-0ba4-11ea-91e9-57248901d932.png)

**Comment by patriksvensson** [comment]
@mholo65 What does your Program.cs look like? There are tests that prove that it returns `-1` if an exception is thrown. Are you returning the value from app.Run(args) in your `Program.cs`?

```csharp
using Spectre.Cli;

namespace Test
{
    public static class Program
    {
        public static int Main(string[] args)
        {
            var app = new CommandApp();
            app.Configure(config =>
            {
                // Build
                config.AddCommand<FooCommand>("foo");
                });
            });

            return app.Run(args);
        }
    }
}
```

**Comment by mholo65** [comment]
@patriksvensson basically the same, only difference I use `await app.RunAsync(args)` instead.

**Comment by patriksvensson** [comment]
@mholo65 I cannot reproduce this. Would you mind creating a reproducable example of the problem you're experiencing?

![image](https://user-images.githubusercontent.com/357872/69410014-6a270e80-0d0a-11ea-8511-7f574efdde8d.png)

**Comment by mholo65** [comment]
@patriksvensson nvm, I'm stupid... I didn't return the exit code from `RunAsync`
![image](https://user-images.githubusercontent.com/7863439/69411159-12da6b80-0d15-11ea-8c5b-48a9d0dcf3c2.png)

**Comment by patriksvensson** [comment]
Pro tip: Unless you handle the exceptions, you shouldn't set `PropagateExceptions'.

**Comment by mholo65** [comment]
> 
> 
> Pro tip: Unless you handle the exceptions, you shouldn't set `PropagateExceptions'.

Yeah, that was just me trying to get an non-zero exit code with a unhandled exception.
