### ISSUE TITLE
Bug when option string value starts with -

### ISSUE THREAD

**Issue by daveaglick** [spectresystems/spectre.cli#91]
It appears there's a bug when the string value of an option starts with a dash:

```
> app -x "-1234"
Error: Short option does not have a valid name.

       -x -1234
           ^ Not a valid name for a short option
```

**Comment by patriksvensson** [comment]
@daveaglick Not really a bug per se. The .NET command line parser uses the [CommandLineToArgvW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw) under the hood which does all kinds of strange parsing. One of these strange things is removing `"` from arguments unless the argument contains some kind of white space.

A work around would be to encode the argument:

```
> app -x \"-1234\"
```

Personally, I think this is super unintuitive so I will look into it some more. 
Perhaps adding a `Run(string)` overload where you can pass `Environment.CommandLine`?

**Comment by daveaglick** [comment]
Gotcha - so by the time you see the `string[] args` the quotes have been stripped off and it looks like another option. I'd definitely say that's bug...it's just not _your_ bug 😂.

Using `Environment.CommandLine` and then handling the splitting yourself certainly seems like it would be a good way to address this (assuming you want to). That would also open some additional capabilities like being able to pass in an arbitrary unsplit string or plugging in different splitting behavior.

**Comment by patriksvensson** [comment]
@daveaglick Yeah, I think I have a solution to this that will work. Will be a breaking change though, but should be easy to fix.

**Comment by patriksvensson** [comment]
@daveaglick Since this is a PowerShell issue and escaping is needed, I'm going to close this now. Perhaps we can make this more tolerant in the future in the parser if there's a need for it.
