### ISSUE TITLE
Is there support for a dictionary argument?

### ISSUE THREAD

**Issue by mgnslndh** [spectresystems/spectre.cli#92]
Let's say I want to supply a list of key/value pairs as arguments to a program. Is it possible with Spectre.Cli? I suppose I could use a string argument and then split/parse the content but I wonder if there is "native" support for a argument of type `IDictionary<string,string>` or something similar.

**Comment by patriksvensson** [comment]
@mgnslndh Yes, you should be able to use `--foo bar --baz qux --baz corge` and access them via the `IRemainingArguments` property of the `CommandContext` which expose a `ILookup<string, string?>` and a `IReadOnlyList<string>`.

Make sure that you've not set parsing mode to `Strict` for this to work.

**Comment by mgnslndh** [comment]
I was hoping for something like this :)

```
--variable key=value --variable key=value
```

```
public class MySettings
{
    [CommandOption("--variable")]    
    public IDictionary<string,string> Variables
}
```

**Comment by patriksvensson** [comment]
@mgnslndh I think that should be possible. I’ll try to find a solution to your problem tonight when I’m at a computer.

**Comment by patriksvensson** [comment]
@mgnslndh Here is a way of accomplishing what you want to do. Since you, in theory, could have duplicate keys, I would recommend going with a `ILookup` instead of a dictionary.

```csharp
using Spectre.Cli;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;

namespace CliTest
{
    public class Program
    {
        public static int Main(string[] args)
        {
            var app = new CommandApp();
            app.SetDefaultCommand<MyCommand>();
            return app.Run(args);
        }
    }

    public sealed class MyCommand : Command<MyCommand.Settings>
    {
        public sealed class Settings : CommandSettings
        {
            [CommandOption("--variable <VALUE>")]
            [TypeConverter(typeof(TupleTypeConverter))]
            public Tuple<string, string>[] Items { get; set; }

            // Declare a dictionary where we can access the variables
            // via a dicionary instead of a tuple array.
            public Dictionary<string, string> Variables { get; private set; }

            // Use the Validation method to initialize the dictionary.
            // A bit hackish, but it gets the work done.
            public override ValidationResult Validate()
            {
                Items ??= new Tuple<string, string>[] { };
                Variables = Items?.ToDictionary(x => x.Item1, y => y.Item2);
                return ValidationResult.Success();
            }
        }

        public override int Execute(CommandContext context, Settings settings)
        {
            // Write the content of the dictionary to the console.
            foreach (var (key, value) in settings.Variables)
            {
                Console.WriteLine($"{key} => {value}");
            }

            return 0;
        }
    }
    
    // Use a custom TypeConverter to extract the data to a tuple
    public sealed class TupleTypeConverter : TypeConverter
    {
        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
        {
            if (value is string stringValue)
            {
                var parts = stringValue.Split(new[] { '=' });
                if (parts.Length != 2)
                {
                    throw new InvalidOperationException("Not a tuple!");
                }
                return Tuple.Create(parts[0], parts[1]);
            }
            throw new InvalidOperationException("Expected string");
        }
    }
}
```

**Comment by mgnslndh** [comment]
That works like a charm! Thanks Patrik! 

Is this a feature you would consider having out of the box? 

Ideally you would only be required to declare your option like this and Spectre.Cli would take care of the rest:

```
[CommandOption("--variable <KEY>=<VALUE>")]
public IDictionary<string, string> Variables { get; set; }
```

Other types than `IDictionary` could be supported, like `ILookup` and `IReadOnlyDictionary`.

I guess this is where "opinionated" comes in the picture :) Does this feature belong at all and if so, how should it work if working out of the box. Anyway, i'm happy it is possible to achieve this with your sample above.

**Comment by patriksvensson** [comment]
@mgnslndh Perfect! I'm not opposed to it, but I need to think about how it can be implemented to fit in well with the existing parser. Let me think about it for a little while and I'll get back to you.

**Comment by patriksvensson** [comment]
@mgnslndh I've been thinking now, and will go with something like this:

```csharp
public sealed class Settings : CommandSettings
{
    [CommandOption("--variable <VALUE>")]
    [PairDeconstructor(typeof(MyStringIntDeconstructor))]
    public ILookup<string, int>[] Items { get; set; }
}
```

Where you implement the `PairDeconstructor` like this.

```
public sealed class MyStringIntDeconstructor : PairDeconstructor<string, int>
{
    public (string key, int value) Deconstruct(string value) 
    {
        // Omitted
    }
}
```

Would this work for you?

**Comment by mgnslndh** [comment]
That looks fine by me. I suppose you would get something like "first=1" in `value` and then it would be up to `MyStringIntDeconstructor ` to deconstruct that string into a tuple. So the "key=value" would be the opinionated convention of assigning key/value pairs? Will '=' and '"' characters handled or is that up to the deconstructor function?

**Comment by mgnslndh** [comment]
Found the implementation :) Will look it through.

**Comment by patriksvensson** [comment]
@mgnslndh Correct. I will add a default pair deconstructor that will do this automatically so a pair deconstructor only is necessary if there's no default type converter for the key or value type. That is for another PR though since I want to start small.

**Comment by patriksvensson** [comment]
@mgnslndh Merged this to master and should be out on NuGet without an hour or so.

By default, you can just add an option of `ILookup<T,V>`, `IDictionary<T,V>` or `IReadOnlyDictionary<T,V>`. Any values separated with either `:` or `=` will work. This converts pairs using registered instances of `TypeConverter`, so primitive types and most BCL types should work OOTB.

```csharp
public sealed class Settings : CommandSettings
{
    [CommandOption("--lookup <KEY=SECONDS>")]
    public ILookup<string, int> Lookup { get; set; }
}
```

If you want to do the conversion yourself i.e if there is no default type converter for a type or you want to do some custom parsing, you can point to a deconstructor using the `PairDeconstructor` attribute.

```csharp
public sealed class Settings : CommandSettings
{
    [CommandOption("--env <KEY=MAGIC>")]
    [PairDeconstructor(typeof(MyStringToMagicStuffDeconstructor))]
    public ILookup<string, MagicStuff> Items { get; set; }
}

public sealed class MyStringToMagicStuffDeconstructor : PairDeconstructor<string, MagicStuff>
{
    public (string key, MagicStuff value) Deconstruct(string value) 
    {
        // Omitted
    }
}
```
